<?php
namespace CodingPride\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends DocumentRepository
{
	/**
	 * Tries to find the badge in database. If it's not there, it creates it.
	 * Afterwards, sets the conditions for that badge.
	 *
	 * @param string $badge_name The name of the badge
	 * @param array $conditions The conditions that needs to match this badge
	 * @param string $description A badge description
	 *
	 * @return Badge $badge
	 */
	public function create( $badge_name, $conditions, $description, $pagination_param = '' )
	{
		$badge = $this->findOneByName( $badge_name );

		if ( empty( $badge ) )
		{
			$badge 	= new Badge();
			$badge->setName( $badge_name );
			$badge->setLast_pagination_param( $pagination_param );
			$badge->setDescription( $description );
			$this->dm->persist( $badge );
		}

		$badge->setConditions( $conditions );

		return $badge;
	}
}