<?php
namespace CodingPride\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends DocumentRepository
{
	/*
	const DEFAULT_BADGE_DATE = '2012-01-01';

	public function getBadgesOutOfDate( $badges_to_calculate, \DateTime $date = null )
	{
		$query 		= $this->dm->createQueryBuilder( 'CodingPride\Document\Badge' );
		$badges 	= $query->field( 'last_date_checked' )->lte( new \DateTime() )->getQuery()->execute();
		foreach ( $badges as $badge )
		{
			$badge->setConditions( $badges_to_calculate[$badge->getName()]['conditions'] );
		}
		return $badges;
	}

	public function getLastPaginationParam()
	{
		$badges	= $this->findAll( array( 'active' => 1 ), array(), 1 );
		$badge 	= $badges->getNext();
		return $badge->getLast_pagination_param();
	}

	*/

	public function create( $badge_name, $conditions, $description, $pagination_param = '' )
	{
		$badge = $this->findOneByName( $badge_name );

		if ( empty( $badge ) )
		{
			$badge 	= new Badge();
			$badge->setName( $badge_name );
			$badge->setLast_pagination_param( $pagination_param );
			$badge->setDescription( $description );
			$this->dm->persist( $badge );
			//var_dump( "Persistiendo " . $badge->getName() );	
		}

		$badge->setConditions( $conditions );

		return $badge;
	}

	
}