<?php

namespace Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class CodingPrideDocumentCommitHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['author'])) {
            $reference = $data['author'];
            if (isset($this->class->fieldMappings['author']['simple']) && $this->class->fieldMappings['author']['simple']) {
                $className = $this->class->fieldMappings['author']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['author'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['author']->setValue($document, $return);
            $hydratedData['author'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['date'])) {
            $value = $data['date'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['date']->setValue($document, clone $return);
            $hydratedData['date'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['branch'])) {
            $value = $data['branch'];
            $return = (string) $value;
            $this->class->reflFields['branch']->setValue($document, $return);
            $hydratedData['branch'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['revision'])) {
            $value = $data['revision'];
            $return = (string) $value;
            $this->class->reflFields['revision']->setValue($document, $return);
            $hydratedData['revision'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['files'])) {
            $value = $data['files'];
            $return = $value;
            $this->class->reflFields['files']->setValue($document, $return);
            $hydratedData['files'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['comment'])) {
            $value = $data['comment'];
            $return = (string) $value;
            $this->class->reflFields['comment']->setValue($document, $return);
            $hydratedData['comment'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['parent'])) {
            $value = $data['parent'];
            $return = (int) $value;
            $this->class->reflFields['parent']->setValue($document, $return);
            $hydratedData['parent'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['child'])) {
            $value = $data['child'];
            $return = (int) $value;
            $this->class->reflFields['child']->setValue($document, $return);
            $hydratedData['child'] = $return;
        }
        return $hydratedData;
    }
}